version: '3.8'

services:
  cantina-backend:
    image: cantina-backend:latest
    build:
      context: https://github.com/leomiler/sistema-cantina.git
      dockerfile: server/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=mysql://cantina_user:cantina123@tasks.mysql:3306/cantina
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        # Traefik configuration
        - "traefik.enable=true"
        - "traefik.http.routers.cantina-backend.rule=Host(`cantina.srv920656.hstgr.cloud`) && PathPrefix(`/api`)"
        - "traefik.http.routers.cantina-backend.entrypoints=websecure"
        - "traefik.http.routers.cantina-backend.tls.certresolver=letsencrypt"
        - "traefik.http.services.cantina-backend.loadbalancer.server.port=3001"
        # Security headers
        - "traefik.http.middlewares.cantina-backend-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
        - "traefik.http.routers.cantina-backend.middlewares=cantina-backend-headers"
    networks:
      - traefik-public
      - cantina-network

  cantina-frontend:
    image: cantina-frontend:latest
    build:
      context: https://github.com/leomiler/sistema-cantina.git
      dockerfile: client/Dockerfile
    depends_on:
      - cantina-backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        # Traefik configuration
        - "traefik.enable=true"
        - "traefik.http.routers.cantina-frontend.rule=Host(`cantina.srv920656.hstgr.cloud`)"
        - "traefik.http.routers.cantina-frontend.entrypoints=websecure"
        - "traefik.http.routers.cantina-frontend.tls.certresolver=letsencrypt"
        - "traefik.http.services.cantina-frontend.loadbalancer.server.port=80"
        # Security headers
        - "traefik.http.middlewares.cantina-frontend-headers.headers.frameDeny=true"
        - "traefik.http.middlewares.cantina-frontend-headers.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.cantina-frontend-headers.headers.browserXssFilter=true"
        - "traefik.http.middlewares.cantina-frontend-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
        - "traefik.http.routers.cantina-frontend.middlewares=cantina-frontend-headers"
        # HTTP to HTTPS redirect
        - "traefik.http.routers.cantina-frontend-http.rule=Host(`cantina.srv920656.hstgr.cloud`)"
        - "traefik.http.routers.cantina-frontend-http.entrypoints=web"
        - "traefik.http.routers.cantina-frontend-http.middlewares=cantina-redirect-to-https"
        - "traefik.http.middlewares.cantina-redirect-to-https.redirectscheme.scheme=https"
    networks:
      - traefik-public
      - cantina-network

networks:
  traefik-public:
    external: true
  cantina-network:
    driver: overlay
    attachable: true