version: '3.8'

services:
  cantina-backend:
    image: node:18-alpine
    command: >
      sh -c "
        apk add --no-cache git &&
        git clone https://github.com/leomiler/sistema-cantina.git /app &&
        cd /app/server &&
        npm install &&
        npm install -g typescript &&
        npx prisma generate &&
        npm run build &&
        node dist/index.js
      "
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=mysql://cantina_user:cantina123@tasks.mysql:3306/cantina
    ports:
      - "3001:3001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cantina-backend.rule=Host(`cantina.srv920656.hstgr.cloud`) && PathPrefix(`/api`)"
        - "traefik.http.routers.cantina-backend.entrypoints=websecure"
        - "traefik.http.routers.cantina-backend.tls.certresolver=letsencrypt"
        - "traefik.http.services.cantina-backend.loadbalancer.server.port=3001"
    networks:
      - traefik-public
      - default

networks:
  traefik-public:
    external: true
  default:
    driver: overlay